#%RAML 0.8
title: Test
baseUri: http://www.google.com
/a:
  get:
    displayName: Test
    description: Test endpoint.
    queryParameters:
      q:
        displayName: Viva Peron
        description: Viva Peron
        type: string
    body:
      application/xml: !!null
    responses:
      404:
        description: |
          Not found
        headers:
          X-Content-Type-Options:
            type: string
            required: false
          X-XSS-Protection:
            type: string
            required: false
        body:
          text/html: !!null
/:
  post:
    displayName: Post test
    description: Test POST call
    headers:
      test:
        type: string
        required: true
      test2:
        type: string
        required: false
    body:
      application/xml: !!null
    responses:
      405:
        description: Method Not Allowed
        headers:
          X-XSS-Protection:
            type: string
            required: false
        body:
          text/html: !!null
  delete:
    displayName: Delete test
    description: Test DELETE call
    responses:
      405:
        description: Method Not Allowed
        headers:
          X-XSS-Protection:
            type: string
            required: false
        body:
          text/html: !!null
